import type { HeliosItem } from './types.js';

type GlobalRecord = Pick<HeliosItem, 'id' | 'record_kind' | 'title' | 'summary'
  | 'organization_name' | 'country' | 'place_label' | 'pin_meaning' | 'schedule_text'
  | 'latitude' | 'longitude' | 'source_url' | 'action_url' | 'action_kind'
  | 'action_label' | 'action_note' | 'starts_at'> & { cause_tags: string[]; source_checked_at?: string };

function item(record: GlobalRecord): HeliosItem {
  return {
    ...record,
    availability_status: 'not_confirmed',
    source_checked_at: record.source_checked_at ?? '2026-10-03T17:54:00Z',
    review_due_at: record.source_checked_at
      ? new Date(Date.parse(record.source_checked_at) + 7 * 86400000).toISOString()
      : '2026-10-10T17:54:00Z',
    publication_state: 'curated_demo',
    action_authority: 'provider',
  };
}

export const globalCatalog: HeliosItem[] = [
  item({
    id: 'dcck-klein-center-volunteer', record_kind: 'volunteer', title: 'Prepare community meals in Washington',
    source_checked_at: '2026-10-03T21:00:00Z',
    summary: 'DC Central Kitchen invites volunteers to help prepare meals at its Klein Center in Washington, DC.',
    organization_name: 'DC Central Kitchen', country: 'United States', place_label: 'Washington, DC',
    pin_meaning: 'organization_city', schedule_text: 'Daily morning and weekday evening shifts; check the portal',
    latitude: 38.8646, longitude: -77.0092, cause_tags: ['food', 'hunger', 'community'],
    source_url: 'https://dccentralkitchen.org/volunteer/',
    action_url: 'https://dcck.appianportals.com/dcck-volunteer-registration',
    action_kind: 'registration_page', action_label: 'Open volunteer portal',
    action_note: 'The official portal lists shifts up to three months ahead. Volunteers must be at least 12 and sign a waiver.',
    starts_at: null,
  }),
  item({
    id: 'red-cross-lakewood-alarms-2026', record_kind: 'event', title: 'Install free smoke alarms in Lakewood',
    summary: 'The American Red Cross Los Angeles Region lists a Sound the Alarm event in Lakewood. Check the official shift finder for current registration.',
    organization_name: 'American Red Cross', country: 'United States', place_label: 'Lakewood, California',
    pin_meaning: 'event_city', schedule_text: '17 October 2026, 8:30 am to 2:00 pm local time',
    latitude: 33.8536, longitude: -118.1339, cause_tags: ['disaster', 'safety', 'housing'],
    source_url: 'https://www.redcross.org/local/california/los-angeles.html',
    action_url: 'https://www.redcross.org/local/california/los-angeles/about-us/news-and-events/events/sound-the-alarm-lakewood.html',
    action_kind: 'registration_page', action_label: 'Find a volunteer shift',
    action_note: 'The event page links to a shift finder. Confirm the Lakewood shift and its availability there.',
    starts_at: '2026-10-17T15:30:00Z',
  }),
  item({
    id: 'british-red-cross-volunteer', record_kind: 'volunteer', title: 'Find a British Red Cross volunteer role',
    summary: 'Browse local and remote roles in emergency response, refugee support, charity shops and other services. Applicants must reside in the UK.',
    organization_name: 'British Red Cross', country: 'United Kingdom', place_label: 'London, United Kingdom',
    pin_meaning: 'organization_city', schedule_text: 'Roles vary by location and availability',
    latitude: 51.5074, longitude: -0.1278, cause_tags: ['disaster', 'refugees', 'health'],
    source_url: 'https://www.redcross.org.uk/get-involved/volunteer',
    action_url: 'https://volunteer.redcross.org.uk/opportunities', action_kind: 'role_directory',
    action_label: 'Browse open roles', action_note: 'Applicants must reside in the UK. Check each role’s location and requirements.',
    starts_at: null,
  }),
  item({
    id: 'australian-red-cross-volunteer', record_kind: 'volunteer', title: 'Volunteer with Australian Red Cross',
    summary: 'Explore community roles in emergency response, migration support, aged care and local shops.',
    organization_name: 'Australian Red Cross', country: 'Australia', place_label: 'Sydney, Australia',
    pin_meaning: 'organization_city', schedule_text: 'Roles vary by location and availability',
    latitude: -33.8688, longitude: 151.2093, cause_tags: ['disaster', 'refugees', 'seniors'],
    source_url: 'https://www.redcross.org.au/volunteer/', action_url: 'https://www.redcross.org.au/volunteer/',
    action_kind: 'role_directory', action_label: 'Explore volunteer roles',
    action_note: 'Choose a local role and check its application requirements with Australian Red Cross.',
    starts_at: null,
  }),
  item({
    id: 'food-bank-singapore-warehouse', record_kind: 'volunteer', title: 'Sort and pack food in Singapore',
    summary: 'Warehouse volunteers sort, pack and organize donated food for beneficiary partners.',
    organization_name: 'The Food Bank Singapore', country: 'Singapore', place_label: 'Singapore',
    pin_meaning: 'organization_city', schedule_text: 'Weekday three-hour sessions; confirm an available place',
    latitude: 1.3, longitude: 103.8, cause_tags: ['food', 'hunger'],
    source_url: 'https://foodbank.sg/volunteer/', action_url: 'https://foodbank.sg/volunteer/',
    action_kind: 'interest_form', action_label: 'Register interest',
    action_note: 'Warehouse sessions are on weekdays and require volunteers to be at least 16. The organization confirms places.',
    starts_at: null,
  }),
  item({
    id: 'lagos-food-bank-volunteer', record_kind: 'volunteer', title: 'Help fight hunger in Lagos',
    summary: 'Volunteer to collect, sort, pack and distribute food through Lagos Food Bank Initiative programs.',
    organization_name: 'Lagos Food Bank Initiative', country: 'Nigeria', place_label: 'Lagos, Nigeria',
    pin_meaning: 'organization_city', schedule_text: 'Programs run throughout the year; confirm a place',
    latitude: 6.5244, longitude: 3.3792, cause_tags: ['food', 'hunger', 'health'],
    source_url: 'https://lagosfoodbank.org/become-a-volunteer/',
    action_url: 'https://lagosfoodbank.org/become-a-volunteer/',
    action_kind: 'registration_page', action_label: 'Read requirements and register',
    action_note: 'Outreach requires registration and confirmation. The organization lists a required branded shirt and its price.',
    starts_at: null,
  }),
  item({
    id: 'foodforward-sa-cape-town', record_kind: 'volunteer', title: 'Arrange a team food bank session in Cape Town',
    summary: 'FoodForward SA welcomes teams for warehouse volunteering that includes sorting and packing food.',
    organization_name: 'FoodForward SA', country: 'South Africa', place_label: 'Cape Town, South Africa',
    pin_meaning: 'organization_city', schedule_text: 'Contact the organization for a team session and availability',
    latitude: -33.9249, longitude: 18.4241, cause_tags: ['food', 'hunger'],
    source_url: 'https://www.foodforwardsa.org/take-action/', action_url: 'https://www.foodforwardsa.org/take-action/',
    action_kind: 'contact_page', action_label: 'Contact FoodForward SA',
    action_note: 'The official page provides a contact route for corporate teams. No session is reserved.',
    starts_at: null,
  }),
  item({
    id: 'techo-chile-colecta-2026', record_kind: 'event', title: 'Join TECHO Chile volunteer fundraising drive',
    summary: 'TECHO Chile lists a 22 to 25 October 2026 collection across Chile supporting housing and community work.',
    organization_name: 'TECHO Chile', country: 'Chile', place_label: 'Santiago, Chile',
    pin_meaning: 'organization_city', schedule_text: '22 to 25 October 2026; confirm your meeting point',
    latitude: -33.4489, longitude: -70.6693, cause_tags: ['housing', 'community'],
    source_url: 'https://cl.techo.org/colecta-techo-2026-sumate-como-voluntario-y-moviliza-el-cambio/',
    action_url: 'https://forms.gle/YaTyBQTfq6J8pe4E8', action_kind: 'interest_form',
    action_label: 'Open TECHO signup form', action_note: 'The collection runs across Chile. The Santiago pin is not a meeting point.',
    starts_at: null,
  }),
  item({
    id: 'techo-guatemala-quetzaltenango', record_kind: 'volunteer', title: 'Join TECHO in Quetzaltenango',
    summary: 'Register interest in TECHO Guatemala housing and community action; the organization shares future activities.',
    organization_name: 'TECHO Guatemala', country: 'Guatemala', place_label: 'Quetzaltenango, Guatemala',
    pin_meaning: 'organization_city', schedule_text: '2026 volunteer campaign; check for upcoming activities',
    latitude: 14.8347, longitude: -91.5181, cause_tags: ['housing', 'community'],
    source_url: 'https://actividades.techo.org/actividades/35546',
    action_url: 'https://actividades.techo.org/inscripciones/actividad/35546',
    action_kind: 'registration_page', action_label: 'Start TECHO registration',
    action_note: 'Login or registration is required. No specific shift is confirmed here.',
    starts_at: null,
  }),
  item({
    id: 'unv-online-volunteering', record_kind: 'volunteer', title: 'Find remote UN Online Volunteering assignments',
    summary: 'United Nations Volunteers lists online assignments. Eligible people can apply from anywhere.',
    organization_name: 'United Nations Volunteers', country: 'Global', place_label: 'Bonn, Germany (UNV headquarters)',
    pin_meaning: 'organization_city', schedule_text: 'Assignments and eligibility vary; confirm on the official platform',
    latitude: 50.7374, longitude: 7.0982, cause_tags: ['remote', 'education', 'community'],
    source_url: 'https://www.unv.org/become-online-volunteer?page=1',
    action_url: 'https://www.unv.org/become-volunteer/',
    action_kind: 'assignment_directory', action_label: 'Find online assignments',
    action_note: 'Assignments are remote and applicants must be at least 18. Choose a current assignment on the UNV platform.',
    starts_at: null,
  }),
  item({
    id: 'banco-alimentos-buenos-aires-volunteer', record_kind: 'volunteer', title: 'Volunteer with Banco de Alimentos Buenos Aires',
    source_checked_at: '2026-10-03T21:00:00Z',
    summary: 'The food bank invites people to register their interest in volunteer tasks through its official form.',
    organization_name: 'Banco de Alimentos Buenos Aires', country: 'Argentina', place_label: 'Buenos Aires, Argentina',
    pin_meaning: 'organization_city', schedule_text: 'Tasks and dates depend on the organization’s response',
    latitude: -34.6037, longitude: -58.3816, cause_tags: ['food', 'hunger', 'community'],
    source_url: 'https://www.bancodealimentos.org.ar/nosotros/si-te-queres-sumar-como-voluntario-dejanos-tus-datos/',
    action_url: 'https://www.bancodealimentos.org.ar/nosotros/si-te-queres-sumar-como-voluntario-dejanos-tus-datos/',
    action_kind: 'interest_form', action_label: 'Open volunteer form',
    action_note: 'The official form asks for contact details, task interests and area of residence. This pin is not a shift location.',
    starts_at: null,
  }),
  item({
    id: 'restos-paris-volunteer', record_kind: 'volunteer', title: 'Find a food relief role in Paris',
    source_checked_at: '2026-10-03T21:00:00Z',
    summary: 'Les Restos du Cœur Paris invites volunteers to browse current roles or offer their time through its local association.',
    organization_name: 'Les Restos du Cœur Paris', country: 'France', place_label: 'Paris, France',
    pin_meaning: 'organization_city', schedule_text: 'Roles and schedules vary; check current Paris listings',
    latitude: 48.8566, longitude: 2.3522, cause_tags: ['food', 'hunger', 'community'],
    source_url: 'https://ad75.restosducoeur.org/devenir-benevole/',
    action_url: 'https://ad75.restosducoeur.org/devenir-benevole/',
    action_kind: 'role_directory', action_label: 'Browse Paris roles',
    action_note: 'Choose a current listing or submit a volunteer offer. The city pin is not a meeting point.',
    starts_at: null,
  }),
  item({
    id: 'foodsharing-kenya-volunteer', record_kind: 'volunteer', title: 'Join food rescue work in Nairobi',
    source_checked_at: '2026-10-03T21:00:00Z',
    summary: 'FoodSharing Kenya recruits community and university volunteers for food rescue, sorting and distribution.',
    organization_name: 'FoodSharing Kenya', country: 'Kenya', place_label: 'Nairobi, Kenya',
    pin_meaning: 'organization_city', schedule_text: 'Activities vary; onboarding follows the application',
    latitude: -1.2864, longitude: 36.8172, cause_tags: ['food', 'hunger', 'environment'],
    source_url: 'https://www.foodsharingke.org/get-involved/volunteer-with-us',
    action_url: 'https://docs.google.com/forms/d/e/1FAIpQLScbJqRJ_lUKtfpAgU55HMd3RV0FAw6GeMWuKJU0WcD51uxVDg/viewform',
    action_kind: 'interest_form', action_label: 'Open volunteer application',
    action_note: 'The form is linked from FoodSharing Kenya. The organization sends onboarding instructions; no activity is reserved.',
    starts_at: null,
  }),
  item({
    id: 'robin-hood-army-delhi', record_kind: 'volunteer', title: 'Join a Robin Hood Army food drive',
    source_checked_at: '2026-10-03T21:00:00Z',
    summary: 'Join the volunteer-run Robin Hood Army and connect with a local chapter for surplus-food distribution.',
    organization_name: 'Robin Hood Army', country: 'India', place_label: 'Delhi, India',
    pin_meaning: 'organization_city', schedule_text: 'Local chapter activities vary; coordinate after joining',
    latitude: 28.6139, longitude: 77.209, cause_tags: ['food', 'hunger', 'community'],
    source_url: 'https://robinhoodarmy.com/sites/main/join-us',
    action_url: 'https://robinhoodarmy.com/sites/main/join-us',
    action_kind: 'registration_page', action_label: 'Open official join page',
    action_note: 'The join page leads to volunteer signup. Confirm an active Delhi chapter and activity before attending.',
    starts_at: null,
  }),
  item({
    id: 'ozharvest-melbourne-volunteer', record_kind: 'volunteer', title: 'Explore OzHarvest volunteer roles in Melbourne',
    source_checked_at: '2026-10-03T21:00:00Z',
    summary: 'OzHarvest offers food rescue, meal preparation and community roles across Australia, including Melbourne.',
    organization_name: 'OzHarvest', country: 'Australia', place_label: 'Melbourne, Australia',
    pin_meaning: 'organization_city', schedule_text: 'Roles vary; most shifts are weekdays during business hours',
    latitude: -37.8136, longitude: 144.9631, cause_tags: ['food', 'hunger', 'environment'],
    source_url: 'https://www.ozharvest.org/volunteer/',
    action_url: 'https://ozharvest.rosterfy.com.au/roles/list',
    action_kind: 'role_directory', action_label: 'Browse OzHarvest roles',
    action_note: 'Filter the official role portal for Melbourne. Training and a police check may be required.',
    starts_at: null,
  }),
];
