import type { HeliosItem } from './types.js';
import { item, type GlobalRecord } from './globalRecord.js';

const sourced = (record: Omit<GlobalRecord, 'source_checked_at'>): HeliosItem =>
  item({ ...record, source_checked_at: '2026-10-03T21:20:00Z' });

export const expandedGlobalCatalog: HeliosItem[] = [
  sourced({
    id: 'daily-bread-toronto-volunteer', record_kind: 'volunteer', title: 'Volunteer with Daily Bread in Toronto',
    summary: 'Daily Bread lists food sorting, kitchen, and food bank roles at its South Etobicoke facility.',
    organization_name: 'Daily Bread Food Bank', country: 'Canada', place_label: 'Toronto, Ontario',
    pin_meaning: 'organization_city', schedule_text: 'Roles and available shifts vary; register on the official page',
    latitude: 43.605, longitude: -79.505, cause_tags: ['food', 'hunger', 'community'],
    source_url: 'https://www.dailybread.ca/get-involved/volunteer/individual-volunteering/',
    action_url: 'https://www.dailybread.ca/get-involved/volunteer/individual-volunteering/',
    action_kind: 'registration_page', action_label: 'See volunteer registration',
    action_note: 'Most roles are at 191 New Toronto Street. Register and confirm a shift with Daily Bread.', starts_at: null,
  }),
  sourced({
    id: 'bamx-mexico-volunteer', record_kind: 'volunteer', title: 'Find a local food bank volunteer path in Mexico',
    summary: 'Red BAMX connects individual volunteers to food banks for sorting and packing food.',
    organization_name: 'Red BAMX', country: 'Mexico', place_label: 'Mexico City, Mexico',
    pin_meaning: 'organization_city', schedule_text: 'Choose a local food bank and confirm its requirements',
    latitude: 19.4326, longitude: -99.1332, cause_tags: ['food', 'hunger', 'environment'],
    source_url: 'https://voluntariado.bamx.org.mx/voluntariado-individual',
    action_url: 'https://voluntariado.bamx.org.mx/voluntariado-individual',
    action_kind: 'official_page', action_label: 'Explore individual volunteering',
    action_note: 'The Mexico City pin is the network office, not a confirmed shift. Local banks set their own requirements and may request a voluntary contribution.', starts_at: null,
  }),
  sourced({
    id: 'acao-cidadania-digital-volunteer', record_kind: 'volunteer', title: 'Support Ação da Cidadania online',
    summary: 'Ação da Cidadania invites digital volunteers to help share its anti-hunger campaign.',
    organization_name: 'Ação da Cidadania', country: 'Brazil', place_label: 'Rio de Janeiro, Brazil',
    pin_meaning: 'organization_city', schedule_text: 'Digital support; check the organization’s current instructions',
    latitude: -22.9068, longitude: -43.1729, cause_tags: ['food', 'hunger', 'remote'],
    source_url: 'https://www.acaodacidadania.org.br/como-apoiar',
    action_url: 'https://www.acaodacidadania.org.br/como-apoiar',
    action_kind: 'official_page', action_label: 'See ways to support',
    action_note: 'This is a remote path. The Rio pin marks the organization, not an activity location.', starts_at: null,
  }),
  sourced({
    id: 'boroume-athens-volunteer', record_kind: 'volunteer', title: 'Help Boroume rescue food in Greece',
    summary: 'Boroume invites volunteers for food rescue coordination, farmers markets, and gleaning.',
    organization_name: 'Boroume', country: 'Greece', place_label: 'Athens, Greece',
    pin_meaning: 'organization_city', schedule_text: 'Programs vary; Boroume contacts volunteers as needs arise',
    latitude: 37.9838, longitude: 23.7275, cause_tags: ['food', 'hunger', 'environment'],
    source_url: 'https://www.boroume.gr/en/you-can-help/become-a-member-of-boroumes-volunteer-team/',
    action_url: 'https://www.boroume.gr/en/you-can-help/become-a-member-of-boroumes-volunteer-team/',
    action_kind: 'interest_form', action_label: 'Open Boroume volunteer form',
    action_note: 'Choose a program and submit interest. The organization confirms participation and location.', starts_at: null,
  }),
  sourced({
    id: 'food-for-all-africa-volunteer', record_kind: 'volunteer', title: 'Volunteer with Food for All Africa',
    summary: 'Food for All Africa invites people to offer time and skills through its official volunteer form.',
    organization_name: 'Food for All Africa', country: 'Ghana', place_label: 'Greater Accra, Ghana',
    pin_meaning: 'organization_city', schedule_text: 'Roles and timing depend on the organization’s response',
    latitude: 5.6037, longitude: -0.187, cause_tags: ['food', 'hunger', 'environment'],
    source_url: 'https://foodforallafrica.com/volunteer/', action_url: 'https://foodforallafrica.com/volunteer/',
    action_kind: 'interest_form', action_label: 'Open volunteer form',
    action_note: 'The regional pin is not a shift location. Contact the organization for role and place details.', starts_at: null,
  }),
  sourced({
    id: 'second-harvest-japan-volunteer', record_kind: 'volunteer', title: 'Volunteer with Second Harvest Japan',
    summary: 'Second Harvest Japan lists food sorting and packing activities and first-time volunteer registration.',
    organization_name: 'Second Harvest Japan', country: 'Japan', place_label: 'Tokyo, Japan',
    pin_meaning: 'organization_city', schedule_text: 'Activities vary; check the reservation system',
    latitude: 35.6762, longitude: 139.6503, cause_tags: ['food', 'hunger'],
    source_url: 'https://2hj.org/english/volunteer/', action_url: 'https://2hj.org/english/volunteer/',
    action_kind: 'registration_page', action_label: 'Read guidelines and register',
    action_note: 'First-time volunteers register before reserving. Some activities are outside Tokyo; check each listing.', starts_at: null,
  }),
  sourced({
    id: 'foodbank-indonesia-volunteer', record_kind: 'volunteer', title: 'Ask Foodbank of Indonesia about volunteering',
    summary: 'Foodbank of Indonesia invites people and community groups to take part in food access programs.',
    organization_name: 'Foodbank of Indonesia', country: 'Indonesia', place_label: 'Jakarta, Indonesia',
    pin_meaning: 'organization_city', schedule_text: 'Contact the organization for a current volunteer path',
    latitude: -6.2088, longitude: 106.8456, cause_tags: ['food', 'hunger', 'community'],
    source_url: 'https://foodbankindonesia.org/en/aksi-bersama/',
    action_url: 'https://foodbankindonesia.org/en/hubungi-kami/',
    action_kind: 'contact_page', action_label: 'Contact Foodbank of Indonesia',
    action_note: 'The official site lists volunteering and a contact route, but no specific shift is confirmed.', starts_at: null,
  }),
  sourced({
    id: 'new-zealand-red-cross-volunteer', record_kind: 'volunteer', title: 'Find a New Zealand Red Cross role',
    summary: 'New Zealand Red Cross lists volunteer roles across more than 50 locations.',
    organization_name: 'New Zealand Red Cross', country: 'New Zealand', place_label: 'Wellington, New Zealand',
    pin_meaning: 'organization_city', schedule_text: 'Filter the role directory for location and availability',
    latitude: -41.2866, longitude: 174.7756, cause_tags: ['disaster', 'refugees', 'community'],
    source_url: 'https://www.redcross.org.nz/get-involved/volunteer/apply-to-volunteer',
    action_url: 'https://www.redcross.org.nz/get-involved/volunteer/apply-to-volunteer',
    action_kind: 'role_directory', action_label: 'Browse available roles',
    action_note: 'Applicants must be based in New Zealand and have the legal right to volunteer there. Wellington is not a specific role location.', starts_at: null,
  }),
];
